In [65]:
import torch
from torch import nn
import torchvision
import numpy as np

In [72]:
a = torch.tensor([[2,-1,1,4,-2],[3,-4,1,6,-5]], dtype = float)
a = a.T
print(a.shape)

torch.Size([5, 2])


In [58]:
b = torchvision.transforms.Normalize(a)
print(b)

TypeError: Normalize.__init__() missing 1 required positional argument: 'std'

In [73]:
mean_std = torch.std_mean(a,dim=0)
print(mean_std)

(tensor([2.3875, 4.6583], dtype=torch.float64), tensor([0.8000, 0.2000], dtype=torch.float64))


In [126]:
c = (a-mean_std[1])/mean_std[0]
print(c)
tester = c
print(tester)

tensor([[ 0.5026,  0.6011],
        [-0.7539, -0.9016],
        [ 0.0838,  0.1717],
        [ 1.3403,  1.2451],
        [-1.1728, -1.1163]], dtype=torch.float64)
tensor([[ 0.5026,  0.6011],
        [-0.7539, -0.9016],
        [ 0.0838,  0.1717],
        [ 1.3403,  1.2451],
        [-1.1728, -1.1163]], dtype=torch.float64)


In [127]:
convdayroi = torch.matmul(tester.T,tester)/4
print(convdayroi)

tensor([[1.0000, 0.9936],
        [0.9936, 1.0000]], dtype=torch.float64)


In [129]:
mean_0 = torch.mean(tester[0:3],dim =0) # 1 x 2
print("mean_0",mean_0)
smean_0 = tester - mean_0
sw_0 = torch.matmul(smean_0.T,smean_0)


mean_1 = torch.mean(tester[3:5],dim=0) # 1 x 2
print("mean_1",mean_1)
smean_1 = tester - mean_1
sw_1 = torch.matmul(smean_1.T,smean_1)

print("sw_0",sw_0)
print("sw_1",sw_1)

scatter_within = sw_0 + sw_1

scatter_within = torch.inverse(scatter_within)
print("scatter_within", scatter_within)


mean_0 tensor([-0.0558, -0.0429], dtype=torch.float64)
mean_1 tensor([0.0838, 0.0644], dtype=torch.float64)
sw_0 tensor([[4.0156, 3.9862],
        [3.9862, 4.0092]], dtype=torch.float64)
sw_1 tensor([[4.0351, 4.0012],
        [4.0012, 4.0207]], dtype=torch.float64)
scatter_within tensor([[ 9.4793, -9.4292],
        [-9.4292,  9.5038]], dtype=torch.float64)


In [130]:
mean_0 = mean_0.view(1,-1)
print(mean_0.shape)
print(mean_0)

mean_1 = mean_1.view(1,-1)
print(mean_1.shape)

torch.Size([1, 2])
tensor([[-0.0558, -0.0429]], dtype=torch.float64)
torch.Size([1, 2])


In [124]:
scatter_between = torch.matmul(mean_0.T,mean_0)*3 + torch.matmul(mean_1.T,mean_1)*2
print("scatter_between",scatter_between)

scatter_between tensor([[0.0234, 0.0180],
        [0.0180, 0.0138]], dtype=torch.float64)


In [131]:
scatter_matrix = scatter_within*scatter_between
print(scatter_matrix)

tensor([[ 0.2217, -0.1696],
        [-0.1696,  0.1314]], dtype=torch.float64)


In [132]:
out = torch.linalg.svd(scatter_matrix)
print(out)

torch.return_types.linalg_svd(
U=tensor([[-0.7929,  0.6093],
        [ 0.6093,  0.7929]], dtype=torch.float64),
S=tensor([0.3520, 0.0011], dtype=torch.float64),
Vh=tensor([[-0.7929,  0.6093],
        [ 0.6093,  0.7929]], dtype=torch.float64))


In [59]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [83]:
x = np.array([[2,-1,1,4,-2],[3,-4,1,6,-5]]).T
x = x.reshape(5,2)
x_std = sc.fit_transform(x)
print(x_std)

[[ 0.56195149  0.67202151]
 [-0.84292723 -1.00803226]
 [ 0.09365858  0.19200614]
 [ 1.4985373   1.39204455]
 [-1.31122014 -1.24803994]]


In [78]:
another_c = torch.tensor(x_std)
print(another_c)

tensor([[ 0.5620,  0.6720],
        [-0.8429, -1.0080],
        [ 0.0937,  0.1920],
        [ 1.4985,  1.3920],
        [-1.3112, -1.2480]], dtype=torch.float64)


In [88]:

cova = torch.cov(c.T)
print(cova)

tensor([[1.0000, 0.9936],
        [0.9936, 1.0000]], dtype=torch.float64)


In [87]:
print(x_std)
cov_mat = np.cov(x_std.T)
print(cov_mat)

[[ 0.56195149  0.67202151]
 [-0.84292723 -1.00803226]
 [ 0.09365858  0.19200614]
 [ 1.4985373   1.39204455]
 [-1.31122014 -1.24803994]]
[[1.25       1.24195253]
 [1.24195253 1.25      ]]
